# Mock track database for offline/fallback recommendation generation.
# Contains 39 tracks across multiple genres with full audio features.

MOCK_TRACKS = [
    {
        "id": "2ctvdKmETxmdKPcSpIPVLF",
        "name": "Breathe (In the Air)",
        "artists": [{"name": "Pink Floyd"}],
        "album": {"name": "The Dark Side of the Moon", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273ea7caaff71da1040afd49437"}]},
        "popularity": 72,
        "external_urls": {"spotify": "https://open.spotify.com/track/2ctvdKmETxmdKPcSpIPVLF"},
        "uri": "spotify:track:2ctvdKmETxmdKPcSpIPVLF",
        "valence": 0.28,
        "energy": 0.36,
        "danceability": 0.48,
        "acousticness": 0.35,
        "instrumentalness": 0.60,
        "genres": ["classic rock", "psychedelic rock", "rock"]
    },
    {
        "id": "5L8rp5N79n66aD5mblOjCr",
        "name": "Fake Plastic Trees",
        "artists": [{"name": "Radiohead"}],
        "album": {"name": "The Bends", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2733d994fe88aa8d9518d6174a7"}]},
        "popularity": 69,
        "external_urls": {"spotify": "https://open.spotify.com/track/5L8rp5N79n66aD5mblOjCr"},
        "uri": "spotify:track:5L8rp5N79n66aD5mblOjCr",
        "valence": 0.14,
        "energy": 0.32,
        "danceability": 0.39,
        "acousticness": 0.64,
        "instrumentalness": 0.05,
        "genres": ["alternative rock", "art rock", "rock", "indie"]
    },
    {
        "id": "1HtxGCsjuaokdASW95dBN3",
        "name": "Intro",
        "artists": [{"name": "The xx"}],
        "album": {"name": "xx", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273d61184ff211d2da5308b26e0"}]},
        "popularity": 71,
        "external_urls": {"spotify": "https://open.spotify.com/track/1HtxGCsjuaokdASW95dBN3"},
        "uri": "spotify:track:1HtxGCsjuaokdASW95dBN3",
        "valence": 0.40,
        "energy": 0.25,
        "danceability": 0.62,
        "acousticness": 0.58,
        "instrumentalness": 0.85,
        "genres": ["indie pop", "downtempo", "indie", "electronic"]
    },
    {
        "id": "6DESft0qm6RhoYf5wzeoGH",
        "name": "Holocene",
        "artists": [{"name": "Bon Iver"}],
        "album": {"name": "Bon Iver", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273b5e40e21a22144d363ef873e"}]},
        "popularity": 70,
        "external_urls": {"spotify": "https://open.spotify.com/track/6DESft0qm6RhoYf5wzeoGH"},
        "uri": "spotify:track:6DESft0qm6RhoYf5wzeoGH",
        "valence": 0.22,
        "energy": 0.18,
        "danceability": 0.38,
        "acousticness": 0.82,
        "instrumentalness": 0.30,
        "genres": ["indie folk", "singer-songwriter", "acoustic", "indie"]
    },
    {
        "id": "69kOkLUCkxizYvxL58z52a",
        "name": "Get Lucky",
        "artists": [{"name": "Daft Punk"}],
        "album": {"name": "Random Access Memories", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273b06dbd081f211516e9d6d376"}]},
        "popularity": 82,
        "external_urls": {"spotify": "https://open.spotify.com/track/69kOkLUCkxizYvxL58z52a"},
        "uri": "spotify:track:69kOkLUCkxizYvxL58z52a",
        "valence": 0.82,
        "energy": 0.81,
        "danceability": 0.79,
        "acousticness": 0.04,
        "instrumentalness": 0.00,
        "genres": ["electronic", "dance", "pop"]
    },
    {
        "id": "7ppafa1bHHKsNlP2N7H5Fz",
        "name": "Ocean Eyes",
        "artists": [{"name": "Billie Eilish"}],
        "album": {"name": "Don't Smile at Me", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2732bb49abef0a6c0b05b63004b"}]},
        "popularity": 84,
        "external_urls": {"spotify": "https://open.spotify.com/track/7ppafa1bHHKsNlP2N7H5Fz"},
        "uri": "spotify:track:7ppafa1bHHKsNlP2N7H5Fz",
        "valence": 0.16,
        "energy": 0.28,
        "danceability": 0.50,
        "acousticness": 0.72,
        "instrumentalness": 0.05,
        "genres": ["pop", "alternative"]
    },
    {
        "id": "7KXjTSCq5nL1LoYtL7XAwS",
        "name": "HUMBLE.",
        "artists": [{"name": "Kendrick Lamar"}],
        "album": {"name": "DAMN.", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2738b52c6b9bc4e43d87386ebf3"}]},
        "popularity": 81,
        "external_urls": {"spotify": "https://open.spotify.com/track/7KXjTSCq5nL1LoYtL7XAwS"},
        "uri": "spotify:track:7KXjTSCq5nL1LoYtL7XAwS",
        "valence": 0.42,
        "energy": 0.81,
        "danceability": 0.90,
        "acousticness": 0.02,
        "instrumentalness": 0.00,
        "genres": ["hip-hop", "rap"]
    },
    {
        "id": "417o069rT8V26j3Z9Z9FjU",
        "name": "Awake",
        "artists": [{"name": "Tycho"}],
        "album": {"name": "Awake", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2738a9d16b539bf34f4be54460d"}]},
        "popularity": 58,
        "external_urls": {"spotify": "https://open.spotify.com/track/417o069rT8V26j3Z9Z9FjU"},
        "uri": "spotify:track:417o069rT8V26j3Z9Z9FjU",
        "valence": 0.40,
        "energy": 0.52,
        "danceability": 0.55,
        "acousticness": 0.12,
        "instrumentalness": 0.82,
        "genres": ["ambient", "electronic", "chill"]
    },
    {
        "id": "4vLYewWIvqHfKtJDk8c8tq",
        "name": "So What",
        "artists": [{"name": "Miles Davis"}],
        "album": {"name": "Kind of Blue", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273a8c17b5e4ff8146745f9ec5f"}]},
        "popularity": 68,
        "external_urls": {"spotify": "https://open.spotify.com/track/4vLYewWIvqHfKtJDk8c8tq"},
        "uri": "spotify:track:4vLYewWIvqHfKtJDk8c8tq",
        "valence": 0.35,
        "energy": 0.16,
        "danceability": 0.52,
        "acousticness": 0.78,
        "instrumentalness": 0.65,
        "genres": ["jazz", "instrumental"]
    },
    {
        "id": "65FftemJ1DmM2H5zC4P8yC",
        "name": "Time",
        "artists": [{"name": "Hans Zimmer"}],
        "album": {"name": "Inception (OST)", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273db06a6c4293f0b2fdfb2fbff"}]},
        "popularity": 74,
        "external_urls": {"spotify": "https://open.spotify.com/track/65FftemJ1DmM2H5zC4P8yC"},
        "uri": "spotify:track:65FftemJ1DmM2H5zC4P8yC",
        "valence": 0.08,
        "energy": 0.28,
        "danceability": 0.18,
        "acousticness": 0.70,
        "instrumentalness": 0.90,
        "genres": ["classical", "instrumental", "focus"]
    },
    {
        "id": "6K4t31amVTZDgR3sKmwUJJ",
        "name": "The Less I Know the Better",
        "artists": [{"name": "Tame Impala"}],
        "album": {"name": "Currents", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2739ec3b4007d4b4a1eb292d314"}]},
        "popularity": 85,
        "external_urls": {"spotify": "https://open.spotify.com/track/6K4t31amVTZDgR3sKmwUJJ"},
        "uri": "spotify:track:6K4t31amVTZDgR3sKmwUJJ",
        "valence": 0.68,
        "energy": 0.74,
        "danceability": 0.78,
        "acousticness": 0.10,
        "instrumentalness": 0.15,
        "genres": ["indie pop", "alternative", "indie", "psychedelic"]
    },
    {
        "id": "7H0ya83CMmgFcOhw0UB6ow",
        "name": "Space Song",
        "artists": [{"name": "Beach House"}],
        "album": {"name": "Depression Cherry", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2730999aa111b7dfb8f2d5f3dfd"}]},
        "popularity": 81,
        "external_urls": {"spotify": "https://open.spotify.com/track/7H0ya83CMmgFcOhw0UB6ow"},
        "uri": "spotify:track:7H0ya83CMmgFcOhw0UB6ow",
        "valence": 0.40,
        "energy": 0.38,
        "danceability": 0.50,
        "acousticness": 0.62,
        "instrumentalness": 0.72,
        "genres": ["dream pop", "indie", "chill", "alternative"]
    },
    {
        "id": "50o7jn1Yh89D4N6d2H128C",
        "name": "Stole the Show",
        "artists": [{"name": "Kygo"}],
        "album": {"name": "Cloud Nine", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273763a8a3ee2643a6d91244ffb"}]},
        "popularity": 76,
        "external_urls": {"spotify": "https://open.spotify.com/track/50o7jn1Yh89D4N6d2H128C"},
        "uri": "spotify:track:50o7jn1Yh89D4N6d2H128C",
        "valence": 0.70,
        "energy": 0.78,
        "danceability": 0.72,
        "acousticness": 0.15,
        "instrumentalness": 0.05,
        "genres": ["electronic", "dance", "pop"]
    },
    {
        "id": "1fEGtTZjrjJW8eUeewnNJR",
        "name": "Flightless Bird, American Mouth",
        "artists": [{"name": "Iron & Wine"}],
        "album": {"name": "The Shepherd's Dog", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b27357c9135fc760cdb3a726be64"}]},
        "popularity": 68,
        "external_urls": {"spotify": "https://open.spotify.com/track/1fEGtTZjrjJW8eUeewnNJR"},
        "uri": "spotify:track:1fEGtTZjrjJW8eUeewnNJR",
        "valence": 0.52,
        "energy": 0.32,
        "danceability": 0.40,
        "acousticness": 0.85,
        "instrumentalness": 0.12,
        "genres": ["folk", "acoustic", "singer-songwriter", "indie"]
    },
    {
        "id": "3G4Vj4q1o1H2E03t73Wl8n",
        "name": "Nothing's Gonna Hurt You Baby",
        "artists": [{"name": "Cigarettes After Sex"}],
        "album": {"name": "I.", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2730b91df131ea7106093d93d3b"}]},
        "popularity": 75,
        "external_urls": {"spotify": "https://open.spotify.com/track/3G4Vj4q1o1H2E03t73Wl8n"},
        "uri": "spotify:track:3G4Vj4q1o1H2E03t73Wl8n",
        "valence": 0.25,
        "energy": 0.22,
        "danceability": 0.38,
        "acousticness": 0.70,
        "instrumentalness": 0.42,
        "genres": ["dream pop", "slowcore", "indie", "romantic"]
    },
    {
        "id": "5Z01UMMf7V1o0MzF86s6WJ",
        "name": "Lose Yourself",
        "artists": [{"name": "Eminem"}],
        "album": {"name": "Curtain Call", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b27320f7f2b1d6db7d4715bd0605"}]},
        "popularity": 85,
        "external_urls": {"spotify": "https://open.spotify.com/track/5Z01UMMf7V1o0MzF86s6WJ"},
        "uri": "spotify:track:5Z01UMMf7V1o0MzF86s6WJ",
        "valence": 0.59,
        "energy": 0.89,
        "danceability": 0.69,
        "acousticness": 0.01,
        "instrumentalness": 0.00,
        "genres": ["hip-hop", "rap", "workout"]
    },
    {
        "id": "3UDj4T2S08X2zS52lC2q5U",
        "name": "Sexual Healing",
        "artists": [{"name": "Marvin Gaye"}],
        "album": {"name": "Midnight Love", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273fb8c8b4ef22822ffb2ffb5ee"}]},
        "popularity": 77,
        "external_urls": {"spotify": "https://open.spotify.com/track/3UDj4T2S08X2zS52lC2q5U"},
        "uri": "spotify:track:3UDj4T2S08X2zS52lC2q5U",
        "valence": 0.62,
        "energy": 0.40,
        "danceability": 0.75,
        "acousticness": 0.35,
        "instrumentalness": 0.00,
        "genres": ["soul", "r-n-b", "romantic"]
    },
    {
        "id": "6gB587sZp8R772xL40t5f5",
        "name": "Chill Lofi Beats",
        "artists": [{"name": "Lofi Fruits Music"}],
        "album": {"name": "Lofi Sleep Fruits", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2734a7fbff77faaff858c07e2bb"}]},
        "popularity": 65,
        "external_urls": {"spotify": "https://open.spotify.com/track/6gB587sZp8R772xL40t5f5"},
        "uri": "spotify:track:6gB587sZp8R772xL40t5f5",
        "valence": 0.45,
        "energy": 0.15,
        "danceability": 0.40,
        "acousticness": 0.75,
        "instrumentalness": 0.85,
        "genres": ["lo-fi", "chill", "study", "lofi"]
    },
    {
        "id": "2hwOoMt0fXtNeH8GxL18Pe",
        "name": "Blue World",
        "artists": [{"name": "Mac Miller"}],
        "album": {"name": "Circles", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273ad4ffbe2e60bf854ffec5fff"}]},
        "popularity": 78,
        "external_urls": {"spotify": "https://open.spotify.com/track/2hwOoMt0fXtNeH8GxL18Pe"},
        "uri": "spotify:track:2hwOoMt0fXtNeH8GxL18Pe",
        "valence": 0.60,
        "energy": 0.68,
        "danceability": 0.72,
        "acousticness": 0.22,
        "instrumentalness": 0.02,
        "genres": ["hip-hop", "rap", "chill"]
    },
    {
        "id": "6LxcPUqx6noURdA5qc4BAT",
        "name": "Motion Sickness",
        "artists": [{"name": "Phoebe Bridgers"}],
        "album": {"name": "Stranger in the Alps", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2730da7bf433a04bc615df1787c"}]},
        "popularity": 73,
        "external_urls": {"spotify": "https://open.spotify.com/track/6LxcPUqx6noURdA5qc4BAT"},
        "uri": "spotify:track:6LxcPUqx6noURdA5qc4BAT",
        "valence": 0.38,
        "energy": 0.45,
        "danceability": 0.52,
        "acousticness": 0.60,
        "instrumentalness": 0.08,
        "genres": ["indie", "alternative", "singer-songwriter", "bittersweet"]
    },
    {
        "id": "7i7XkG0pWv5tN9H6h4X6Lw",
        "name": "Ylang Ylang",
        "artists": [{"name": "FKJ"}],
        "album": {"name": "Ylang Ylang EP", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273d40ec4625b0ff7227d8db191"}]},
        "popularity": 72,
        "external_urls": {"spotify": "https://open.spotify.com/track/7i7XkG0pWv5tN9H6h4X6Lw"},
        "uri": "spotify:track:7i7XkG0pWv5tN9H6h4X6Lw",
        "valence": 0.50,
        "energy": 0.28,
        "danceability": 0.48,
        "acousticness": 0.70,
        "instrumentalness": 0.75,
        "genres": ["jazz", "electronic", "chill", "coffee"]
    },
    {
        "id": "6830xJmG68XhN2n71p1J71",
        "name": "Green Light",
        "artists": [{"name": "Lorde"}],
        "album": {"name": "Melodrama", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273c52a06141a2386fae8568c07"}]},
        "popularity": 77,
        "external_urls": {"spotify": "https://open.spotify.com/track/6830xJmG68XhN2n71p1J71"},
        "uri": "spotify:track:6830xJmG68XhN2n71p1J71",
        "valence": 0.65,
        "energy": 0.78,
        "danceability": 0.70,
        "acousticness": 0.12,
        "instrumentalness": 0.01,
        "genres": ["pop", "alternative", "dance"]
    },
    {
        "id": "61yQP9FDS7ukp4eAVTdwit",
        "name": "Bloodbuzz Ohio",
        "artists": [{"name": "The National"}],
        "album": {"name": "High Violet", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2733d994fe88aa8d9518d6174a7"}]},
        "popularity": 68,
        "external_urls": {"spotify": "https://open.spotify.com/track/61yQP9FDS7ukp4eAVTdwit"},
        "uri": "spotify:track:61yQP9FDS7ukp4eAVTdwit",
        "valence": 0.20,
        "energy": 0.62,
        "danceability": 0.48,
        "acousticness": 0.28,
        "instrumentalness": 0.32,
        "genres": ["alternative rock", "indie rock", "dark", "melancholy"]
    },
    {
        "id": "4NmSJldV83eeGOmvqFgihW",
        "name": "Midnight City",
        "artists": [{"name": "M83"}],
        "album": {"name": "Hurry Up, We're Dreaming", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273ea7caaff71da1040afd49437"}]},
        "popularity": 81,
        "external_urls": {"spotify": "https://open.spotify.com/track/4NmSJldV83eeGOmvqFgihW"},
        "uri": "spotify:track:4NmSJldV83eeGOmvqFgihW",
        "valence": 0.52,
        "energy": 0.78,
        "danceability": 0.70,
        "acousticness": 0.08,
        "instrumentalness": 0.42,
        "genres": ["electronic", "synthpop", "indie", "neon"]
    },
    {
        "id": "0U0ldCRmgCqhVvD6ksG63j",
        "name": "Nightcall",
        "artists": [{"name": "Kavinsky"}],
        "album": {"name": "Outrun", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273fb8c8b4ef22822ffb2ffb5ee"}]},
        "popularity": 79,
        "external_urls": {"spotify": "https://open.spotify.com/track/0U0ldCRmgCqhVvD6ksG63j"},
        "uri": "spotify:track:0U0ldCRmgCqhVvD6ksG63j",
        "valence": 0.30,
        "energy": 0.68,
        "danceability": 0.72,
        "acousticness": 0.12,
        "instrumentalness": 0.45,
        "genres": ["synthwave", "electronic", "dark", "late night", "neon"]
    },
    {
        "id": "3k5oLgungD1dSOGLqQdIQw",
        "name": "Texas Sun",
        "artists": [{"name": "Khruangbin"}],
        "album": {"name": "Texas Sun EP", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273b06dbd081f211516e9d6d376"}]},
        "popularity": 76,
        "external_urls": {"spotify": "https://open.spotify.com/track/3k5oLgungD1dSOGLqQdIQw"},
        "uri": "spotify:track:3k5oLgungD1dSOGLqQdIQw",
        "valence": 0.68,
        "energy": 0.45,
        "danceability": 0.58,
        "acousticness": 0.50,
        "instrumentalness": 0.28,
        "genres": ["indie", "psychedelic", "chill", "sunset"]
    },
    {
        "id": "0u63S1Z30m3W5H0G36z5i9",
        "name": "Ambre",
        "artists": [{"name": "Nils Frahm"}],
        "album": {"name": "Wintermusik", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273db06a6c4293f0b2fdfb2fbff"}]},
        "popularity": 64,
        "external_urls": {"spotify": "https://open.spotify.com/track/0u63S1Z30m3W5H0G36z5i9"},
        "uri": "spotify:track:0u63S1Z30m3W5H0G36z5i9",
        "valence": 0.42,
        "energy": 0.10,
        "danceability": 0.22,
        "acousticness": 0.95,
        "instrumentalness": 0.90,
        "genres": ["classical", "piano", "peaceful", "calm"]
    },
    {
        "id": "5M2P8Rk94u0i39N9bX70rN",
        "name": "Dayvan Cowboy",
        "artists": [{"name": "Boards of Canada"}],
        "album": {"name": "The Campfire Headphase", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2738a9d16b539bf34f4be54460d"}]},
        "popularity": 61,
        "external_urls": {"spotify": "https://open.spotify.com/track/5M2P8Rk94u0i39N9bX70rN"},
        "uri": "spotify:track:5M2P8Rk94u0i39N9bX70rN",
        "valence": 0.38,
        "energy": 0.40,
        "danceability": 0.42,
        "acousticness": 0.30,
        "instrumentalness": 0.80,
        "genres": ["ambient", "electronic", "idm", "nostalgic"]
    },
    {
        "id": "0ofHAoxe9vBkTCp2UQIavz",
        "name": "Dreams",
        "artists": [{"name": "Fleetwood Mac"}],
        "album": {"name": "Rumours", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273a72666a7b7eb74a6f7b3b3cb"}]},
        "popularity": 88,
        "external_urls": {"spotify": "https://open.spotify.com/track/0ofHAoxe9vBkTCp2UQIavz"},
        "uri": "spotify:track:0ofHAoxe9vBkTCp2UQIavz",
        "valence": 0.72,
        "energy": 0.48,
        "danceability": 0.82,
        "acousticness": 0.08,
        "instrumentalness": 0.00,
        "genres": ["classic rock", "rock", "cozy", "nostalgic"]
    },
    {
        "id": "3vQ4T78TTMOjQXGfXVKQJo",
        "name": "Redbone",
        "artists": [{"name": "Childish Gambino"}],
        "album": {"name": "\"Awaken, My Love!\"", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273a8c17b5e4ff8146745f9ec5f"}]},
        "popularity": 83,
        "external_urls": {"spotify": "https://open.spotify.com/track/3vQ4T78TTMOjQXGfXVKQJo"},
        "uri": "spotify:track:3vQ4T78TTMOjQXGfXVKQJo",
        "valence": 0.58,
        "energy": 0.35,
        "danceability": 0.74,
        "acousticness": 0.18,
        "instrumentalness": 0.02,
        "genres": ["soul", "funk", "pop", "romantic"]
    },
    {
        "id": "7ouBSPZKQpm7zQz2leJXta",
        "name": "Tum Hi Ho",
        "artists": [{"name": "Arijit Singh"}],
        "album": {"name": "Aashiqui 2", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b27346d0a7a4a9c8b74681f211ff"}]},
        "popularity": 75,
        "external_urls": {"spotify": "https://open.spotify.com/track/7ouBSPZKQpm7zQz2leJXta"},
        "uri": "spotify:track:7ouBSPZKQpm7zQz2leJXta",
        "valence": 0.30,
        "energy": 0.35,
        "danceability": 0.40,
        "acousticness": 0.75,
        "instrumentalness": 0.00,
        "genres": ["bollywood", "hindi", "romantic", "sad"]
    },
    {
        "id": "6VBhH7CyP56BXjp8VsDFPZ",
        "name": "Kesariya",
        "artists": [{"name": "Arijit Singh"}],
        "album": {"name": "Brahmastra", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273b06dbd081f211516e9d6d376"}]},
        "popularity": 82,
        "external_urls": {"spotify": "https://open.spotify.com/track/6VBhH7CyP56BXjp8VsDFPZ"},
        "uri": "spotify:track:6VBhH7CyP56BXjp8VsDFPZ",
        "valence": 0.60,
        "energy": 0.65,
        "danceability": 0.55,
        "acousticness": 0.30,
        "instrumentalness": 0.00,
        "genres": ["bollywood", "hindi", "romantic", "pop"]
    },
    {
        "id": "7F8RNvTQlvbeBLeenycvN6",
        "name": "Kun Faya Kun",
        "artists": [{"name": "A.R. Rahman"}, {"name": "Javed Ali"}, {"name": "Mohit Chauhan"}],
        "album": {"name": "Rockstar", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273ea7caaff71da1040afd49437"}]},
        "popularity": 78,
        "external_urls": {"spotify": "https://open.spotify.com/track/7F8RNvTQlvbeBLeenycvN6"},
        "uri": "spotify:track:7F8RNvTQlvbeBLeenycvN6",
        "valence": 0.45,
        "energy": 0.38,
        "danceability": 0.35,
        "acousticness": 0.80,
        "instrumentalness": 0.05,
        "genres": ["bollywood", "hindi", "sufi", "calm", "acoustic"]
    },
    {
        "id": "4bD9z9qa4qg9BhryvYWB7c",
        "name": "Kabira",
        "artists": [{"name": "Tochi Raina"}, {"name": "Rekha Bhardwaj"}],
        "album": {"name": "Yeh Jawaani Hai Deewani", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2733d994fe88aa8d9518d6174a7"}]},
        "popularity": 79,
        "external_urls": {"spotify": "https://open.spotify.com/track/4bD9z9qa4qg9BhryvYWB7c"},
        "uri": "spotify:track:4bD9z9qa4qg9BhryvYWB7c",
        "valence": 0.55,
        "energy": 0.45,
        "danceability": 0.60,
        "acousticness": 0.65,
        "instrumentalness": 0.00,
        "genres": ["bollywood", "hindi", "cozy", "acoustic", "folk"]
    },
    {
        "id": "1gJGCMIpebuV2aDX3RAetr",
        "name": "Chaiyya Chaiyya",
        "artists": [{"name": "Sukhwinder Singh"}, {"name": "Sapna Awasthi"}],
        "album": {"name": "Dil Se", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273a8c17b5e4ff8146745f9ec5f"}]},
        "popularity": 74,
        "external_urls": {"spotify": "https://open.spotify.com/track/1gJGCMIpebuV2aDX3RAetr"},
        "uri": "spotify:track:1gJGCMIpebuV2aDX3RAetr",
        "valence": 0.85,
        "energy": 0.88,
        "danceability": 0.75,
        "acousticness": 0.15,
        "instrumentalness": 0.00,
        "genres": ["bollywood", "hindi", "dance", "energetic"]
    },
    {
        "id": "0cJTjTH3XVTTJh8F4Uq1db",
        "name": "Zaalima",
        "artists": [{"name": "Arijit Singh"}, {"name": "Harshdeep Kaur"}],
        "album": {"name": "Raees", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273fb8c8b4ef22822ffb2ffb5ee"}]},
        "popularity": 76,
        "external_urls": {"spotify": "https://open.spotify.com/track/0cJTjTH3XVTTJh8F4Uq1db"},
        "uri": "spotify:track:0cJTjTH3XVTTJh8F4Uq1db",
        "valence": 0.68,
        "energy": 0.70,
        "danceability": 0.62,
        "acousticness": 0.25,
        "instrumentalness": 0.00,
        "genres": ["bollywood", "hindi", "romantic", "pop"]
    },
    {
        "id": "6o1ywd45rTIgLR514Skdtl",
        "name": "Dil Diyan Gallan",
        "artists": [{"name": "Atif Aslam"}],
        "album": {"name": "Tiger Zinda Hai", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273db06a6c4293f0b2fdfb2fbff"}]},
        "popularity": 77,
        "external_urls": {"spotify": "https://open.spotify.com/track/6o1ywd45rTIgLR514Skdtl"},
        "uri": "spotify:track:6o1ywd45rTIgLR514Skdtl",
        "valence": 0.50,
        "energy": 0.42,
        "danceability": 0.52,
        "acousticness": 0.60,
        "instrumentalness": 0.00,
        "genres": ["bollywood", "hindi", "romantic", "calm"]
    },
    {
        "id": "2EFHa4LIYRwILLNvKp8ocE",
        "name": "Senorita",
        "artists": [{"name": "Farhan Akhtar"}, {"name": "Hrithik Roshan"}, {"name": "Abhay Deol"}],
        "album": {"name": "Zindagi Na Milegi Dobara", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2738a9d16b539bf34f4be54460d"}]},
        "popularity": 75,
        "external_urls": {"spotify": "https://open.spotify.com/track/2EFHa4LIYRwILLNvKp8ocE"},
        "uri": "spotify:track:2EFHa4LIYRwILLNvKp8ocE",
        "valence": 0.80,
        "energy": 0.75,
        "danceability": 0.78,
        "acousticness": 0.35,
        "instrumentalness": 0.00,
        "genres": ["bollywood", "hindi", "dance", "upbeat"]
    },
    {
        "id": "39vrbjCMTRXEdiIr2IsBgd",
        "name": "Kar Gayi Chull",
        "artists": [{"name": "Badshah"}, {"name": "Fazilpuria"}, {"name": "Sukriti Kakar"}],
        "album": {"name": "Kapoor & Sons", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273c52a06141a2386fae8568c07"}]},
        "popularity": 74,
        "external_urls": {"spotify": "https://open.spotify.com/track/39vrbjCMTRXEdiIr2IsBgd"},
        "uri": "spotify:track:39vrbjCMTRXEdiIr2IsBgd",
        "valence": 0.78,
        "energy": 0.85,
        "danceability": 0.82,
        "acousticness": 0.10,
        "instrumentalness": 0.00,
        "genres": ["bollywood", "hindi", "punjabi", "party", "energetic"]
    }
]
