# Mock track database for offline/fallback recommendation generation.
# Contains 30 tracks across multiple genres with full audio features.

MOCK_TRACKS = [
    {
        "id": "pink_floyd_breathe",
        "name": "Breathe (In the Air)",
        "artists": [{"name": "Pink Floyd"}],
        "album": {"name": "The Dark Side of the Moon", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273ea7caaff71da1040afd49437"}]},
        "popularity": 72,
        "external_urls": {"spotify": "https://open.spotify.com/track/2ctvdKmETG4z2Kj58wEA71"},
        "uri": "spotify:track:2ctvdKmETG4z2Kj58wEA71",
        "valence": 0.28,
        "energy": 0.36,
        "danceability": 0.48,
        "acousticness": 0.35,
        "instrumentalness": 0.60,
        "genres": ["classic rock", "psychedelic rock", "rock"]
    },
    {
        "id": "radiohead_fake_plastic",
        "name": "Fake Plastic Trees",
        "artists": [{"name": "Radiohead"}],
        "album": {"name": "The Bends", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2733d994fe88aa8d9518d6174a7"}]},
        "popularity": 78,
        "external_urls": {"spotify": "https://open.spotify.com/track/734y1l1j99unYhxY4wCVn9"},
        "uri": "spotify:track:734y1l1j99unYhxY4wCVn9",
        "valence": 0.14,
        "energy": 0.32,
        "danceability": 0.39,
        "acousticness": 0.64,
        "instrumentalness": 0.05,
        "genres": ["alternative rock", "art rock", "rock", "indie"]
    },
    {
        "id": "the_xx_intro",
        "name": "Intro",
        "artists": [{"name": "The xx"}],
        "album": {"name": "xx", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273a72666a7b7eb74a6f7b3b3cb"}]},
        "popularity": 75,
        "external_urls": {"spotify": "https://open.spotify.com/track/5i7ywXG3g75155xW946xNu"},
        "uri": "spotify:track:5i7ywXG3g75155xW946xNu",
        "valence": 0.40,
        "energy": 0.25,
        "danceability": 0.62,
        "acousticness": 0.58,
        "instrumentalness": 0.85,
        "genres": ["indie pop", "downtempo", "indie", "electronic"]
    },
    {
        "id": "bon_iver_holocene",
        "name": "Holocene",
        "artists": [{"name": "Bon Iver"}],
        "album": {"name": "Bon Iver, Bon Iver", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273c52a06141a2386fae8568c07"}]},
        "popularity": 69,
        "external_urls": {"spotify": "https://open.spotify.com/track/4jFA4Vw7955FmH34Bhgl9r"},
        "uri": "spotify:track:4jFA4Vw7955FmH34Bhgl9r",
        "valence": 0.22,
        "energy": 0.18,
        "danceability": 0.38,
        "acousticness": 0.82,
        "instrumentalness": 0.30,
        "genres": ["indie folk", "singer-songwriter", "acoustic", "indie"]
    },
    {
        "id": "daft_punk_get_lucky",
        "name": "Get Lucky",
        "artists": [{"name": "Daft Punk"}],
        "album": {"name": "Random Access Memories", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273b06dbd081f211516e9d6d376"}]},
        "popularity": 82,
        "external_urls": {"spotify": "https://open.spotify.com/track/6913n93Tq7lU2n0H66y788"},
        "uri": "spotify:track:6913n93Tq7lU2n0H66y788",
        "valence": 0.82,
        "energy": 0.81,
        "danceability": 0.79,
        "acousticness": 0.04,
        "instrumentalness": 0.00,
        "genres": ["electronic", "dance", "pop"]
    },
    {
        "id": "billie_eilish_ocean_eyes",
        "name": "Ocean Eyes",
        "artists": [{"name": "Billie Eilish"}],
        "album": {"name": "Don't Smile at Me", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2732bb49abef0a6c0b05b63004b"}]},
        "popularity": 84,
        "external_urls": {"spotify": "https://open.spotify.com/track/7hDV9tEE167j3AFlQAwzgo"},
        "uri": "spotify:track:7hDV9tEE167j3AFlQAwzgo",
        "valence": 0.16,
        "energy": 0.28,
        "danceability": 0.50,
        "acousticness": 0.72,
        "instrumentalness": 0.05,
        "genres": ["pop", "alternative"]
    },
    {
        "id": "kendrick_lamar_humble",
        "name": "HUMBLE.",
        "artists": [{"name": "Kendrick Lamar"}],
        "album": {"name": "DAMN.", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273d40ec4625b0ff7227d8db191"}]},
        "popularity": 86,
        "external_urls": {"spotify": "https://open.spotify.com/track/7KXg897Ftc2Xz55aswR15g"},
        "uri": "spotify:track:7KXg897Ftc2Xz55aswR15g",
        "valence": 0.42,
        "energy": 0.81,
        "danceability": 0.90,
        "acousticness": 0.02,
        "instrumentalness": 0.00,
        "genres": ["hip-hop", "rap"]
    },
    {
        "id": "tycho_awake",
        "name": "Awake",
        "artists": [{"name": "Tycho"}],
        "album": {"name": "Awake", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2738a9d16b539bf34f4be54460d"}]},
        "popularity": 58,
        "external_urls": {"spotify": "https://open.spotify.com/track/5M67k5475u546u5476u547"},
        "uri": "spotify:track:517ywXG3g75155xW946xNu",
        "valence": 0.40,
        "energy": 0.52,
        "danceability": 0.55,
        "acousticness": 0.12,
        "instrumentalness": 0.82,
        "genres": ["ambient", "electronic", "chill"]
    },
    {
        "id": "miles_davis_so_what",
        "name": "So What",
        "artists": [{"name": "Miles Davis"}],
        "album": {"name": "Kind of Blue", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273a8c17b5e4ff8146745f9ec5f"}]},
        "popularity": 68,
        "external_urls": {"spotify": "https://open.spotify.com/track/4vEZ9VR5Up7hIKn68MFmmO"},
        "uri": "spotify:track:4vEZ9VR5Up7hIKn68MFmmO",
        "valence": 0.35,
        "energy": 0.16,
        "danceability": 0.52,
        "acousticness": 0.78,
        "instrumentalness": 0.65,
        "genres": ["jazz", "instrumental"]
    },
    {
        "id": "hans_zimmer_time",
        "name": "Time",
        "artists": [{"name": "Hans Zimmer"}],
        "album": {"name": "Inception (OST)", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273db06a6c4293f0b2fdfb2fbff"}]},
        "popularity": 74,
        "external_urls": {"spotify": "https://open.spotify.com/track/6ZFbXI2wLXRvTy857G6WNz"},
        "uri": "spotify:track:6ZFbXI2wLXRvTy857G6WNz",
        "valence": 0.08,
        "energy": 0.28,
        "danceability": 0.18,
        "acousticness": 0.70,
        "instrumentalness": 0.90,
        "genres": ["classical", "instrumental", "focus"]
    },
    {
        "id": "tame_impala_less_i_know",
        "name": "The Less I Know the Better",
        "artists": [{"name": "Tame Impala"}],
        "album": {"name": "Currents", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2739ec3b4007d4b4a1eb292d314"}]},
        "popularity": 85,
        "external_urls": {"spotify": "https://open.spotify.com/track/6K4t31JmCWuXcrvXjs4evH"},
        "uri": "spotify:track:6K4t31JmCWuXcrvXjs4evH",
        "valence": 0.68,
        "energy": 0.74,
        "danceability": 0.78,
        "acousticness": 0.10,
        "instrumentalness": 0.15,
        "genres": ["indie pop", "alternative", "indie", "psychedelic"]
    },
    {
        "id": "beach_house_space_song",
        "name": "Space Song",
        "artists": [{"name": "Beach House"}],
        "album": {"name": "Depression Cherry", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2730999aa111b7dfb8f2d5f3dfd"}]},
        "popularity": 81,
        "external_urls": {"spotify": "https://open.spotify.com/track/75JFxk2mclGj5J6nJsGJ4L"},
        "uri": "spotify:track:75JFxk2mclGj5J6nJsGJ4L",
        "valence": 0.40,
        "energy": 0.38,
        "danceability": 0.50,
        "acousticness": 0.62,
        "instrumentalness": 0.72,
        "genres": ["dream pop", "indie", "chill", "alternative"]
    },
    {
        "id": "kygo_stole_show",
        "name": "Stole the Show",
        "artists": [{"name": "Kygo"}],
        "album": {"name": "Cloud Nine", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273763a8a3ee2643a6d91244ffb"}]},
        "popularity": 76,
        "external_urls": {"spotify": "https://open.spotify.com/track/55p5p576u546u5476u547"},
        "uri": "spotify:track:7hDV9tEE167j3AFlQAwzgo",
        "valence": 0.70,
        "energy": 0.78,
        "danceability": 0.72,
        "acousticness": 0.15,
        "instrumentalness": 0.05,
        "genres": ["electronic", "dance", "pop"]
    },
    {
        "id": "iron_wine_flightless",
        "name": "Flightless Bird, American Mouth",
        "artists": [{"name": "Iron & Wine"}],
        "album": {"name": "The Shepherd's Dog", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2730da7bf433a04bc615df1787c"}]},
        "popularity": 71,
        "external_urls": {"spotify": "https://open.spotify.com/track/1B412LhHwsr79U5G713N5c"},
        "uri": "spotify:track:1B412LhHwsr79U5G713N5c",
        "valence": 0.52,
        "energy": 0.32,
        "danceability": 0.40,
        "acousticness": 0.85,
        "instrumentalness": 0.12,
        "genres": ["folk", "acoustic", "singer-songwriter", "indie"]
    },
    {
        "id": "cigarettes_nothing",
        "name": "Nothing's Gonna Hurt You Baby",
        "artists": [{"name": "Cigarettes After Sex"}],
        "album": {"name": "I.", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2730b91df131ea7106093d93d3b"}]},
        "popularity": 75,
        "external_urls": {"spotify": "https://open.spotify.com/track/3745k5475u546u5476u547"},
        "uri": "spotify:track:734y1l1j99unYhxY4wCVn9",
        "valence": 0.25,
        "energy": 0.22,
        "danceability": 0.38,
        "acousticness": 0.70,
        "instrumentalness": 0.42,
        "genres": ["dream pop", "slowcore", "indie", "romantic"]
    },
    {
        "id": "eminem_lose_yourself",
        "name": "Lose Yourself",
        "artists": [{"name": "Eminem"}],
        "album": {"name": "Curtain Call: The Hits", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2735d4ffbe4e60bf8045f9ec5ff"}]},
        "popularity": 85,
        "external_urls": {"spotify": "https://open.spotify.com/track/15JFxk2mclGj5J6nJsGJ4L"},
        "uri": "spotify:track:7KXg897Ftc2Xz55aswR15g",
        "valence": 0.59,
        "energy": 0.89,
        "danceability": 0.69,
        "acousticness": 0.01,
        "instrumentalness": 0.00,
        "genres": ["hip-hop", "rap", "workout"]
    },
    {
        "id": "marvin_gaye_healing",
        "name": "Sexual Healing",
        "artists": [{"name": "Marvin Gaye"}],
        "album": {"name": "Midnight Love", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273fb8c8b4ef22822ffb2ffb5ee"}]},
        "popularity": 77,
        "external_urls": {"spotify": "https://open.spotify.com/track/3EO9d3xUpW3L2G45x5y59D"},
        "uri": "spotify:track:3EO9d3xUpW3L2G45x5y59D",
        "valence": 0.62,
        "energy": 0.40,
        "danceability": 0.75,
        "acousticness": 0.35,
        "instrumentalness": 0.00,
        "genres": ["soul", "r-n-b", "romantic"]
    },
    {
        "id": "lofi_fruits_chill",
        "name": "Chill Lofi Beats",
        "artists": [{"name": "Lofi Fruits Music"}],
        "album": {"name": "Lofi Sleep Fruits", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2734a7fbff77faaff858c07e2bb"}]},
        "popularity": 65,
        "external_urls": {"spotify": "https://open.spotify.com/track/4p4p576u546u5476u547"},
        "uri": "spotify:track:5i7ywXG3g75155xW946xNu",
        "valence": 0.45,
        "energy": 0.15,
        "danceability": 0.40,
        "acousticness": 0.75,
        "instrumentalness": 0.85,
        "genres": ["lo-fi", "chill", "study", "lofi"]
    },
    {
        "id": "mac_miller_blue_world",
        "name": "Blue World",
        "artists": [{"name": "Mac Miller"}],
        "album": {"name": "Circles", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273ad4ffbe2e60bf854ffec5fff"}]},
        "popularity": 78,
        "external_urls": {"spotify": "https://open.spotify.com/track/2134k5475u546u5476u547"},
        "uri": "spotify:track:2134k5475u546u5476u547",
        "valence": 0.60,
        "energy": 0.68,
        "danceability": 0.72,
        "acousticness": 0.22,
        "instrumentalness": 0.02,
        "genres": ["hip-hop", "rap", "chill"]
    },
    {
        "id": "phoebe_bridgers_motion",
        "name": "Motion Sickness",
        "artists": [{"name": "Phoebe Bridgers"}],
        "album": {"name": "Stranger in the Alps", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2730da7bf433a04bc615df1787c"}]},
        "popularity": 73,
        "external_urls": {"spotify": "https://open.spotify.com/track/1B412LhHwsr79U5G713N5c"},
        "uri": "spotify:track:1B412LhHwsr79U5G713N5c",
        "valence": 0.38,
        "energy": 0.45,
        "danceability": 0.52,
        "acousticness": 0.60,
        "instrumentalness": 0.08,
        "genres": ["indie", "alternative", "singer-songwriter", "bittersweet"]
    },
    {
        "id": "fkj_ylang_ylang",
        "name": "Ylang Ylang",
        "artists": [{"name": "FKJ"}],
        "album": {"name": "Ylang Ylang EP", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273d40ec4625b0ff7227d8db191"}]},
        "popularity": 72,
        "external_urls": {"spotify": "https://open.spotify.com/track/2ctvdKmETG4z2Kj58wEA71"},
        "uri": "spotify:track:2ctvdKmETG4z2Kj58wEA71",
        "valence": 0.50,
        "energy": 0.28,
        "danceability": 0.48,
        "acousticness": 0.70,
        "instrumentalness": 0.75,
        "genres": ["jazz", "electronic", "chill", "coffee"]
    },
    {
        "id": "lorde_green_light",
        "name": "Green Light",
        "artists": [{"name": "Lorde"}],
        "album": {"name": "Melodrama", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273c52a06141a2386fae8568c07"}]},
        "popularity": 77,
        "external_urls": {"spotify": "https://open.spotify.com/track/6913n93Tq7lU2n0H66y788"},
        "uri": "spotify:track:6913n93Tq7lU2n0H66y788",
        "valence": 0.65,
        "energy": 0.78,
        "danceability": 0.70,
        "acousticness": 0.12,
        "instrumentalness": 0.01,
        "genres": ["pop", "alternative", "dance"]
    },
    {
        "id": "the_national_bloodbuzz",
        "name": "Bloodbuzz Ohio",
        "artists": [{"name": "The National"}],
        "album": {"name": "High Violet", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2733d994fe88aa8d9518d6174a7"}]},
        "popularity": 68,
        "external_urls": {"spotify": "https://open.spotify.com/track/734y1l1j99unYhxY4wCVn9"},
        "uri": "spotify:track:734y1l1j99unYhxY4wCVn9",
        "valence": 0.20,
        "energy": 0.62,
        "danceability": 0.48,
        "acousticness": 0.28,
        "instrumentalness": 0.32,
        "genres": ["alternative rock", "indie rock", "dark", "melancholy"]
    },
    {
        "id": "m83_midnight_city",
        "name": "Midnight City",
        "artists": [{"name": "M83"}],
        "album": {"name": "Hurry Up, We're Dreaming", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273ea7caaff71da1040afd49437"}]},
        "popularity": 81,
        "external_urls": {"spotify": "https://open.spotify.com/track/2ctvdKmETG4z2Kj58wEA71"},
        "uri": "spotify:track:2ctvdKmETG4z2Kj58wEA71",
        "valence": 0.52,
        "energy": 0.78,
        "danceability": 0.70,
        "acousticness": 0.08,
        "instrumentalness": 0.42,
        "genres": ["electronic", "synthpop", "indie", "neon"]
    },
    {
        "id": "kavinsky_nightcall",
        "name": "Nightcall",
        "artists": [{"name": "Kavinsky"}],
        "album": {"name": "Outrun", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273fb8c8b4ef22822ffb2ffb5ee"}]},
        "popularity": 79,
        "external_urls": {"spotify": "https://open.spotify.com/track/3EO9d3xUpW3L2G45x5y59D"},
        "uri": "spotify:track:3EO9d3xUpW3L2G45x5y59D",
        "valence": 0.30,
        "energy": 0.68,
        "danceability": 0.72,
        "acousticness": 0.12,
        "instrumentalness": 0.45,
        "genres": ["synthwave", "electronic", "dark", "late night", "neon"]
    },
    {
        "id": "khruangbin_texas_sun",
        "name": "Texas Sun",
        "artists": [{"name": "Khruangbin"}],
        "album": {"name": "Texas Sun EP", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273b06dbd081f211516e9d6d376"}]},
        "popularity": 76,
        "external_urls": {"spotify": "https://open.spotify.com/track/6913n93Tq7lU2n0H66y788"},
        "uri": "spotify:track:6913n93Tq7lU2n0H66y788",
        "valence": 0.68,
        "energy": 0.45,
        "danceability": 0.58,
        "acousticness": 0.50,
        "instrumentalness": 0.28,
        "genres": ["indie", "psychedelic", "chill", "sunset"]
    },
    {
        "id": "nils_frahm_ambre",
        "name": "Ambre",
        "artists": [{"name": "Nils Frahm"}],
        "album": {"name": "Wintermusik", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273db06a6c4293f0b2fdfb2fbff"}]},
        "popularity": 64,
        "external_urls": {"spotify": "https://open.spotify.com/track/6ZFbXI2wLXRvTy857G6WNz"},
        "uri": "spotify:track:6ZFbXI2wLXRvTy857G6WNz",
        "valence": 0.42,
        "energy": 0.10,
        "danceability": 0.22,
        "acousticness": 0.95,
        "instrumentalness": 0.90,
        "genres": ["classical", "piano", "peaceful", "calm"]
    },
    {
        "id": "boards_canada_dayvan",
        "name": "Dayvan Cowboy",
        "artists": [{"name": "Boards of Canada"}],
        "album": {"name": "The Campfire Headphase", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b2738a9d16b539bf34f4be54460d"}]},
        "popularity": 61,
        "external_urls": {"spotify": "https://open.spotify.com/track/5M67k5475u546u5476u547"},
        "uri": "spotify:track:517ywXG3g75155xW946xNu",
        "valence": 0.38,
        "energy": 0.40,
        "danceability": 0.42,
        "acousticness": 0.30,
        "instrumentalness": 0.80,
        "genres": ["ambient", "electronic", "idm", "nostalgic"]
    },
    {
        "id": "fleetwood_dreams",
        "name": "Dreams",
        "artists": [{"name": "Fleetwood Mac"}],
        "album": {"name": "Rumours", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273a72666a7b7eb74a6f7b3b3cb"}]},
        "popularity": 88,
        "external_urls": {"spotify": "https://open.spotify.com/track/085pc2nsCwXMIh3j55liSp"},
        "uri": "spotify:track:085pc2nsCwXMIh3j55liSp",
        "valence": 0.72,
        "energy": 0.48,
        "danceability": 0.82,
        "acousticness": 0.08,
        "instrumentalness": 0.00,
        "genres": ["classic rock", "rock", "cozy", "nostalgic"]
    },
    {
        "id": "childish_redbone",
        "name": "Redbone",
        "artists": [{"name": "Childish Gambino"}],
        "album": {"name": "\"Awaken, My Love!\"", "images": [{"url": "https://i.scdn.co/image/ab67616d0000b273a8c17b5e4ff8146745f9ec5f"}]},
        "popularity": 83,
        "external_urls": {"spotify": "https://open.spotify.com/track/3EO9d3xUpW3L2G45x5y59D"},
        "uri": "spotify:track:3EO9d3xUpW3L2G45x5y59D",
        "valence": 0.58,
        "energy": 0.35,
        "danceability": 0.74,
        "acousticness": 0.18,
        "instrumentalness": 0.02,
        "genres": ["soul", "funk", "pop", "romantic"]
    }
]
